# Autogenerated wrapper script for MGARD_jll for x86_64-apple-darwin
export libmgard

using LLVMOpenMP_jll
using Zlib_jll
using Zstd_jll
using protoc_jll
JLLWrappers.@generate_wrapper_header("MGARD")
JLLWrappers.@declare_library_product(libmgard, "@rpath/libmgard.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll, Zlib_jll, Zstd_jll, protoc_jll)
    JLLWrappers.@init_library_product(
        libmgard,
        "lib/libmgard.1.6.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
